version: '3'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php
    container_name: php
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./web:/var/www
      # - ./web/storage:/var/www/storage
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    extra_hosts:
      - "db.localhost:host-gateway"
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www
      # - ./web/storage:/var/www/storage
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    extra_hosts:
      - "db.localhost:host-gateway"
    networks:
      - app-network

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      MYSQL_DATABASE: test-db
      MYSQL_ROOT_PASSWORD: "test1234"
      TZ: "Asia/Bangkok"
    command: >
      --event-scheduler=ON
      --skip-name-resolve
      --max-connections=1000
      --character-set-server=utf8
      --collation-server=utf8_general_ci
    restart: always
    networks:
      - app-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOSTS: db.localhost
      PMA_USER: root
      PMA_PASSWORD: test1234
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
    volumes:
      - ./config.inc.php:/etc/phpmyadmin/config.inc.php
    ports:
      - "8080:80"
    networks:
      - app-network

  # SFTP/SSH Service (root access)
  sftp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh
    restart: always
    ports:
      - "2222:22"
    volumes:
      - ./web:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
